version: '3'

services:
  lab:
    build: ./
    image: civis-gcp-transition
    container_name: civis-gcp-transition
    volumes:
     - ./:/app
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - POSTGRES_URI=${POSTGRES_URI}
    command: ["/bin/sh","-c","pip install -e /app && jupyter-lab --no-browser --ip=\"*\" --allow-root --port=8888 --NotebookApp.notebook_dir=/app --NotebookApp.terminado_settings='{\"shell_command\": [\"bash\"]}' --LabApp.token=\"\" --LabApp.password=\"\""]